<?php

namespace App\Http\Controllers\Admin;

use A17\Twill\Http\Controllers\Admin\ModuleController as BaseModuleController;
use Illuminate\Support\Facades\Cache;
use Spatie\ResponseCache\Facades\ResponseCache;

class ExhibitionController extends BaseModuleController
{
    protected $moduleName = 'exhibitions';

    protected $permalinkBase = 'exhibition';

//    protected $defaultOrders = ['id' => 'desc'];

    protected $indexOptions = [
        'reorder' => true,
    ];

    public function reorder()
    {
        Cache::flush();
        ResponseCache::clear();
        return parent::reorder(); // TODO: Change the autogenerated stub
    }
}
