<?php

namespace App\Http\Controllers\Admin;

use A17\Twill\Http\Controllers\Admin\ModuleController as BaseModuleController;
use App\Repositories\WorkRepository;
use Illuminate\Support\Facades\Cache;
use Spatie\ResponseCache\Facades\ResponseCache;

class WorkController extends BaseModuleController
{
    protected $moduleName = 'works';

    protected $permalinkBase = 'work';

//    protected $defaultOrders = ['id' => 'desc'];

    protected $indexOptions = [
        'reorder' => true,
    ];

    protected function formData($request)
    {
        $works = app(WorkRepository::class)->listAll('title',[],$request->route('work'));
        $works->prepend('Kérem válasszon','0');

        return [
          'works' => $works
        ];
    }

    protected $indexColumns = [
        'title' => [
            'title' => 'Title',
            'field' => 'title',
        ],
        'reference_number' => [
            'title' => 'Referenciaszám',
            'field' => 'reference_number',
        ],
        'parent' => [
            'title' => 'Szülő',
            'sort' => true,
            'relationship' => 'parent',
            'field' => 'title'
        ],
    ];

    public function reorder()
    {
        Cache::flush();
        ResponseCache::clear();
        return parent::reorder(); // TODO: Change the autogenerated stub
    }
}
