<?php

namespace App\Repositories;

use A17\Twill\Repositories\Behaviors\HandleTranslations;
use A17\Twill\Repositories\Behaviors\HandleSlugs;
use A17\Twill\Repositories\Behaviors\HandleMedias;
use A17\Twill\Repositories\ModuleRepository;
use App\Models\Exhibition;
use Illuminate\Support\Facades\Cache;
use Spatie\ResponseCache\Facades\ResponseCache;

class ExhibitionRepository extends ModuleRepository
{
    use HandleTranslations, HandleSlugs, HandleMedias;

    public function __construct(Exhibition $model)
    {
        $this->model = $model;
    }

    public function afterSave($object, $fields)
    {
        Cache::flush();
        ResponseCache::clear();
        parent::afterSave($object, $fields); // TODO: Change the autogenerated stub
    }
}
