<?php

namespace App\Repositories;

use A17\Twill\Repositories\Behaviors\HandleTags;
use A17\Twill\Repositories\Behaviors\HandleTranslations;
use A17\Twill\Repositories\Behaviors\HandleSlugs;
use A17\Twill\Repositories\Behaviors\HandleMedias;
use A17\Twill\Repositories\Behaviors\HandleFiles;
use A17\Twill\Repositories\ModuleRepository;
use App\Models\Work;
use Illuminate\Support\Facades\Log;

class WorkRepository extends ModuleRepository
{
    use HandleTranslations, HandleSlugs, HandleMedias, HandleFiles, HandleTags;

    public function __construct(Work $model)
    {
        $this->model = $model;
    }

    public function afterSave($object, $fields)
    {
        if (isset($fields['parent_work_id']) && $fields['parent_work_id'] == 0) {
            $object->parent_work_id = null;
            $object->save();
        }

        parent::afterSave($object, $fields); // TODO: Change the autogenerated stub
    }
}
